when:
  - author:
      teamIs:
        - rubik-fp-squad
      ignore:
        nameIs:
    assign:
      teams:
        - rubik-fp-squad
  - author:
      teamIs:
        - kirigami
      ignore:
        nameIs:
    assign:
      teams:
        - kirigami
