language: php

dist: trusty

sudo: false

cache:
  directories:
    - vendor
    - node_modules
    - $HOME/.npm
    - $HOME/.composer/cache

branches:
  only:
    - master
    - /release\/.*/

before_install:
  - timedatectl
  - nvm install
  - npm rebuild

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      composer install --no-dev
      # also installs woocommerce plugin
      bash tests/bin/install-wp-tests.sh wgpb_admin root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer install
    fi
jobs:
    fast_finish: true
    include:
        - stage: build tests
          name: PHP 7.1/unit-tests/Latest WP
          php: 7.1
          env:
            - WP_VERSION=latest
          script:
            - phpunit
        - name: PHP 5.6/unit-tests/Latest WP
          php: 5.6
          env:
            - WP_VERSION=latest
          script:
            - phpunit
        - name: PHP Linting Check
          php: 7.1
          env:
            - WP_TRAVISCI=phpcs
          script:
            - npm run lint:php
        - name: Javascript Tests
          script:
            - npm install
            - npm run test
        - name: Javascript/CSS Lint and Bundle Size Check
          script:
            - npm install
            - npm run build:ci
