version: '3.7'

services:

  db:
    image: mariadb:10.4
    restart: on-failure
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

  wordpress-www:
    depends_on:
      - db
    build:
      context: ./bin/docker/wordpress
    ports:
      - ${WORDPRESS_PORT}:80
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST:
      WORDPRESS_DB_NAME:
      WORDPRESS_DB_USER:
      WORDPRESS_DB_PASSWORD:
      WORDPRESS_TABLE_PREFIX:
      WORDPRESS_DEBUG:
    volumes:
      - "./:/var/www/html/wp-content/plugins/woocommerce-gutenberg-products-block"
      - wordpress:/var/www/html

  wordpress-cli:
    depends_on:
      - db
      - wordpress-www
    build:
        context: ./bin/docker/wp-cli
    restart: on-failure
    environment:
        WORDPRESS_HOST:
        WORDPRESS_TITLE:
        WORDPRESS_LOGIN:
        WORDPRESS_PASSWORD:
        WORDPRESS_PORT:
        WORDPRESS_EMAIL:
        DOMAIN_NAME:
    volumes:
      - ./:/var/www/html/wp-content/plugins/woocommerce-gutenberg-products-block
      - wordpress:/var/www/html

volumes:
  db:
  wordpress:
