export const wooCommerceAPIResponse = [
	{
		id: 15,
		name: 'Album',
		slug: 'album',
		permalink: 'http://your-shop-domain/hoodie-with-logo/music/album/',
		date_created: '2023-04-19T12:15:04',
		date_created_gmt: '2023-04-19T12:15:04',
		date_modified: '2023-04-19T12:15:15',
		date_modified_gmt: '2023-04-19T12:15:15',
		type: 'simple',
		status: 'publish',
		featured: false,
		catalog_visibility: 'visible',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum tincidunt. Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non metus. Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut turpis pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec erat pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.',
		short_description: 'This is a simple, virtual product.',
		sku: 'woo-album',
		price: '15',
		regular_price: '15',
		sale_price: '',
		date_on_sale_from: null,
		date_on_sale_from_gmt: null,
		date_on_sale_to: null,
		date_on_sale_to_gmt: null,
		on_sale: false,
		purchasable: true,
		total_sales: 0,
		virtual: true,
		downloadable: true,
		downloads: [
			{
				id: '47e4cef1-e656-41b7-b922-1610e6f63a6a',
				name: 'Single 1',
				file: 'https://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2017/08/single.jpg',
			},
			{
				id: '9d205e64-847c-4112-b843-c1f02e80a284',
				name: 'Single 2',
				file: 'https://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2017/08/album.jpg',
			},
		],
		download_limit: 1,
		download_expiry: 1,
		external_url: '',
		button_text: '',
		tax_status: 'taxable',
		tax_class: '',
		manage_stock: false,
		stock_quantity: null,
		backorders: 'no',
		backorders_allowed: false,
		backordered: false,
		low_stock_amount: null,
		sold_individually: false,
		weight: '',
		dimensions: {
			length: '',
			width: '',
			height: '',
		},
		shipping_required: false,
		shipping_taxable: false,
		shipping_class: '',
		shipping_class_id: 0,
		reviews_allowed: true,
		average_rating: '0',
		rating_count: 0,
		upsell_ids: [],
		cross_sell_ids: [],
		parent_id: 0,
		purchase_note: '',
		categories: [
			{
				id: 7,
				name: 'Music',
				slug: 'music',
			},
		],
		tags: [],
		images: [
			{
				id: 44,
				date_created: '2023-04-19T12:15:15',
				date_created_gmt: '2023-04-19T12:15:15',
				date_modified: '2023-04-19T12:15:15',
				date_modified_gmt: '2023-04-19T12:15:15',
				src: 'http://your-shop-domain/wp-content/uploads/2023/04/album-1.jpg',
				name: 'album-1.jpg',
				alt: '',
			},
		],
		attributes: [],
		default_attributes: [],
		variations: [],
		grouped_products: [],
		menu_order: 0,
		price_html:
			'<span class="woocommerce-Price-amount amount"><bdi>15,00&nbsp;<span class="woocommerce-Price-currencySymbol">&#122;&#322;</span></bdi></span>',
		related_ids: [ 16 ],
		meta_data: [
			{
				id: 550,
				key: '_wpcom_is_markdown',
				value: '1',
			},
		],
		stock_status: 'instock',
		has_options: false,
		permalink_template:
			'http://your-shop-domain/hoodie-with-logo/music/%pagename%/',
		generated_slug: 'album',
		_links: {
			self: [
				{
					href: 'http://your-shop-domain/wp-json/wc/v3/products/15',
				},
			],
			collection: [
				{
					href: 'http://your-shop-domain/wp-json/wc/v3/products',
				},
			],
		},
	},
	{
		id: 7,
		name: 'Beanie',
		slug: 'beanie',
		permalink:
			'http://your-shop-domain/hoodie-with-logo/clothing/accessories/beanie/',
		date_created: '2023-04-19T12:15:04',
		date_created_gmt: '2023-04-19T12:15:04',
		date_modified: '2023-04-19T12:15:10',
		date_modified_gmt: '2023-04-19T12:15:10',
		type: 'simple',
		status: 'publish',
		featured: false,
		catalog_visibility: 'visible',
		description:
			'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.',
		short_description: 'This is a simple product.',
		sku: 'woo-beanie',
		price: '18',
		regular_price: '20',
		sale_price: '18',
		date_on_sale_from: null,
		date_on_sale_from_gmt: null,
		date_on_sale_to: null,
		date_on_sale_to_gmt: null,
		on_sale: true,
		purchasable: true,
		total_sales: 0,
		virtual: false,
		downloadable: false,
		downloads: [],
		download_limit: 0,
		download_expiry: 0,
		external_url: '',
		button_text: '',
		tax_status: 'taxable',
		tax_class: '',
		manage_stock: false,
		stock_quantity: null,
		backorders: 'no',
		backorders_allowed: false,
		backordered: false,
		low_stock_amount: null,
		sold_individually: false,
		weight: '',
		dimensions: {
			length: '',
			width: '',
			height: '',
		},
		shipping_required: true,
		shipping_taxable: true,
		shipping_class: '',
		shipping_class_id: 0,
		reviews_allowed: true,
		average_rating: '0',
		rating_count: 0,
		upsell_ids: [],
		cross_sell_ids: [],
		parent_id: 0,
		purchase_note: '',
		categories: [
			{
				id: 6,
				name: 'Accessories',
				slug: 'accessories',
			},
		],
		tags: [],
		images: [
			{
				id: 36,
				date_created: '2023-04-19T12:15:10',
				date_created_gmt: '2023-04-19T12:15:10',
				date_modified: '2023-04-19T12:15:10',
				date_modified_gmt: '2023-04-19T12:15:10',
				src: 'http://your-shop-domain/wp-content/uploads/2023/04/beanie-2.jpg',
				name: 'beanie-2.jpg',
				alt: '',
			},
		],
		attributes: [
			{
				id: 1,
				name: 'Color',
				position: 0,
				visible: true,
				variation: false,
				options: [ 'Red' ],
			},
		],
		default_attributes: [],
		variations: [],
		grouped_products: [],
		menu_order: 0,
		price_html:
			'<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi>20,00&nbsp;<span class="woocommerce-Price-currencySymbol">&#122;&#322;</span></bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi>18,00&nbsp;<span class="woocommerce-Price-currencySymbol">&#122;&#322;</span></bdi></span></ins>',
		related_ids: [ 8, 193, 195, 9, 24 ],
		meta_data: [
			{
				id: 477,
				key: '_wpcom_is_markdown',
				value: '1',
			},
		],
		stock_status: 'instock',
		has_options: false,
		permalink_template:
			'http://your-shop-domain/hoodie-with-logo/clothing/accessories/%pagename%/',
		generated_slug: 'beanie',
		_links: {
			self: [
				{
					href: 'http://your-shop-domain/wp-json/wc/v3/products/7',
				},
			],
			collection: [
				{
					href: 'http://your-shop-domain/wp-json/wc/v3/products',
				},
			],
		},
	},
];

export const wooCommerceBlocksStoreAPIResponse = [
	{
		id: 15,
		name: 'Album',
		slug: 'album',
		parent: 0,
		type: 'simple',
		variation: '',
		permalink: 'http://your-shop-domain/hoodie-with-logo/music/album/',
		sku: 'woo-album',
		short_description: '<p>This is a simple, virtual product.</p>',
		description:
			'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum tincidunt. Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non metus. Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut turpis pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec erat pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.</p>',
		on_sale: false,
		prices: {
			price: '1500',
			regular_price: '1500',
			sale_price: '1500',
			price_range: null,
			currency_code: 'PLN',
			currency_symbol: 'z\u0142',
			currency_minor_unit: 2,
			currency_decimal_separator: ',',
			currency_thousand_separator: '',
			currency_prefix: '',
			currency_suffix: ' z\u0142',
		},
		price_html:
			'<span class="woocommerce-Price-amount amount">15,00&nbsp;<span class="woocommerce-Price-currencySymbol">&#122;&#322;</span></span>',
		average_rating: '0',
		review_count: 0,
		images: [
			{
				id: 44,
				src: 'http://your-shop-domain/wp-content/uploads/2023/04/album-1.jpg',
				thumbnail:
					'http://your-shop-domain/wp-content/uploads/2023/04/album-1-450x450.jpg',
				srcset: 'http://your-shop-domain/wp-content/uploads/2023/04/album-1.jpg 800w, http://your-shop-domain/wp-content/uploads/2023/04/album-1-450x450.jpg 450w, http://your-shop-domain/wp-content/uploads/2023/04/album-1-100x100.jpg 100w, http://your-shop-domain/wp-content/uploads/2023/04/album-1-600x600.jpg 600w, http://your-shop-domain/wp-content/uploads/2023/04/album-1-300x300.jpg 300w, http://your-shop-domain/wp-content/uploads/2023/04/album-1-150x150.jpg 150w, http://your-shop-domain/wp-content/uploads/2023/04/album-1-768x768.jpg 768w',
				sizes: '(max-width: 800px) 100vw, 800px',
				name: 'album-1.jpg',
				alt: '',
			},
		],
		categories: [
			{
				id: 7,
				name: 'Music',
				slug: 'music',
				link: 'http://your-shop-domain/product-category/music/',
			},
		],
		tags: [],
		attributes: [],
		variations: [],
		has_options: false,
		is_purchasable: true,
		is_in_stock: true,
		is_on_backorder: false,
		low_stock_remaining: null,
		sold_individually: false,
		add_to_cart: {
			text: 'Add to cart',
			description: 'Add &ldquo;Album&rdquo; to your cart',
			url: '?add-to-cart=15',
			minimum: 1,
			maximum: 9999,
			multiple_of: 1,
		},
		extensions: {},
	},
	{
		id: 7,
		name: 'Beanie',
		slug: 'beanie',
		parent: 0,
		type: 'simple',
		variation: '',
		permalink:
			'http://your-shop-domain/hoodie-with-logo/clothing/accessories/beanie/',
		sku: 'woo-beanie',
		short_description: '<p>This is a simple product.</p>',
		description:
			'<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>',
		on_sale: true,
		prices: {
			price: '1800',
			regular_price: '2000',
			sale_price: '1800',
			price_range: null,
			currency_code: 'PLN',
			currency_symbol: 'z\u0142',
			currency_minor_unit: 2,
			currency_decimal_separator: ',',
			currency_thousand_separator: '',
			currency_prefix: '',
			currency_suffix: ' z\u0142',
		},
		price_html:
			'<del aria-hidden="true"><span class="woocommerce-Price-amount amount">20,00&nbsp;<span class="woocommerce-Price-currencySymbol">&#122;&#322;</span></span></del> <ins><span class="woocommerce-Price-amount amount">18,00&nbsp;<span class="woocommerce-Price-currencySymbol">&#122;&#322;</span></span></ins>',
		average_rating: '0',
		review_count: 0,
		images: [
			{
				id: 36,
				src: 'http://your-shop-domain/wp-content/uploads/2023/04/beanie-2.jpg',
				thumbnail:
					'http://your-shop-domain/wp-content/uploads/2023/04/beanie-2-450x450.jpg',
				srcset: 'http://your-shop-domain/wp-content/uploads/2023/04/beanie-2.jpg 801w, http://your-shop-domain/wp-content/uploads/2023/04/beanie-2-450x450.jpg 450w, http://your-shop-domain/wp-content/uploads/2023/04/beanie-2-100x100.jpg 100w, http://your-shop-domain/wp-content/uploads/2023/04/beanie-2-600x600.jpg 600w, http://your-shop-domain/wp-content/uploads/2023/04/beanie-2-300x300.jpg 300w, http://your-shop-domain/wp-content/uploads/2023/04/beanie-2-150x150.jpg 150w, http://your-shop-domain/wp-content/uploads/2023/04/beanie-2-768x768.jpg 768w',
				sizes: '(max-width: 801px) 100vw, 801px',
				name: 'beanie-2.jpg',
				alt: '',
			},
		],
		categories: [
			{
				id: 6,
				name: 'Accessories',
				slug: 'accessories',
				link: 'http://your-shop-domain/product-category/clothing/accessories/',
			},
		],
		tags: [],
		attributes: [
			{
				id: 1,
				name: 'Color',
				taxonomy: 'pa_color',
				has_variations: false,
				terms: [
					{
						id: 13,
						name: 'Red',
						slug: 'red',
					},
				],
			},
		],
		variations: [],
		has_options: false,
		is_purchasable: true,
		is_in_stock: true,
		is_on_backorder: false,
		low_stock_remaining: null,
		sold_individually: false,
		add_to_cart: {
			text: 'Add to cart',
			description: 'Add &ldquo;Beanie&rdquo; to your cart',
			url: '?add-to-cart=7',
			minimum: 1,
			maximum: 9999,
			multiple_of: 1,
		},
		extensions: {},
	},
];
