name: 'Typescript Monitor'
description: 'Check TypesScript errors'
inputs:
    repo-token:
        description: 'GitHub token'
        required: true
    checkstyle:
        description: 'Path checkstyle.xml file of current PR/branch'
        required: true
    checkstyle-trunk:
        description: 'Path checkstyle.xml file of trunk'
        required: true
    create-comment:
        description: 'Create a dedicate comment for this report?'
        required: false
        default: 'true'
outputs:
    comment:
        description: 'Markdown comment'
runs:
    using: 'node16'
    main: 'index.js'
