name: Bundle Size

on: [pull_request]

jobs:
    build-and-size:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 1
            - uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
            - uses: preactjs/compressed-size-action@265b0667736973f2d83b1a35fdc5440d6cb3322e
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  pattern: '{build/**/*.js,build/**/*.css}'
