name: Check Markdown links

on:
    workflow_dispatch:
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions: {}

jobs:
    markdown-link-check:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v3
            - uses: gaurav-nelson/github-action-markdown-link-check@v1
              with:
                  use-quiet-mode: 'yes'
                  use-verbose-mode: 'no'
                  config-file: '.github/workflows/check-doc-links-config.json'
                  folder-path: './docs'
                  file-path: './README.md'
                  max-depth: 3
                  base-branch: 'trunk'
