name: Check Markdown links

on:
  pull_request:
    paths:
      - '**.md'
  workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    markdown-link-check:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Run Markdown link check
              uses: gaurav-nelson/github-action-markdown-link-check@v1
              with:
                  use-quiet-mode: 'yes'
                  config-file: '.github/workflows/check-doc-links-config.json'
                  folder-path: './docs'
                  file-path: './README.md'
                  base-branch: 'trunk'
