name: Check Modified Assets

on:
    pull_request:

jobs:
    compare-assets-with-trunk:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Cache node_modules
              id: cache-node-modules
              uses: actions/cache@v3
              env:
                  cache-name: cache-node-modules
              with:
                  path: node_modules
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

            - name: Setup node version and npm cache
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'

            - name: Install Node Dependencies
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
              run: npm ci --no-optional

            - name: Build Assets
              run: npm run build:check-assets

            - name: Compare Assets
              uses: ./.github/compare-assets
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  compare: assets-list/assets.json
