on:
  pull_request:
    types: [ closed ]

name: Merged Pull Requests

jobs:
  remove_labels:
    name: Remove labels
    runs-on: ubuntu-latest
    steps:
      - uses: mondeja/remove-labels-gh-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            status: ready to merge
