on:
  pull_request:
    types: [ closed ]

name: Merged Pull Requests

jobs:
  remove_labels:
    name: Remove labels
    runs-on: ubuntu-latest
    steps:
      - uses: mondeja/remove-labels-gh-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            status: ready to merge

  milestoneWhenMerged:
    if: github.event.pull_request.merged
    name: Add Milestone
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Latest milestone
        uses: woocommerce/automations@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          automations: assign-milestone
          milestone_bump_strategy: none
