name: 'Monorepo Merge Notices'
on:
  pull_request_target:
    types: [ 'opened' ]
  issues:
    types: [ 'opened' ]
jobs:
  issue_block:
    name: 'Block Issues & Pull Requests'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Add Merge Notice'
        uses: 'actions/github-script@v5'
        with:
          script: |
              github.rest.issues.createComment( {
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'We have merged WooCommerce Blocks into the WooCommerce monorepo. Please open any issues or pull requests \
                in the woocommerce/woocommerce repository.'
              } );
      - name: 'Close'
        uses: 'actions/github-script@v5'
        with:
          script: |
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed'
            });
