name: 'Monorepo Merge Notices'
on:
  pull_request_target:
    types: [ 'opened' ]
  issues:
    types: [ 'opened' ]
jobs:
  issue_block:
    name: 'Block Issues & Pull Requests'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Add Merge Notice'
        uses: 'actions/github-script@v5'
        with:
          script: |
              github.rest.issues.createComment( {
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'WooCommerce Blocks [has been merged into the WooCommerce Monorepo](https://developer.woo.com/2023/12/01/woocommerce-blocks-merging-into-the-woocommerce-monorepo/).\n\n\
                From now on, please open any issues or pull requests in the [woocommerce/woocommerce](https://github.com/woocommerce/woocommerce) repository.\n\n\
                Thank you!'
              } );
      - name: 'Close'
        uses: 'actions/github-script@v5'
        with:
          script: |
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed'
            });
