name: Nightly builds
on:
  schedule:
    - cron: '0 0 * * *' # Run at 12 AM UTC.
  workflow_dispatch:
jobs:
  build:
    name: Nightly builds
    strategy:
      fail-fast: false
      matrix:
        build: [trunk]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.build }}

      - name: Install Node Dependencies
        run: npm ci --no-optional

      - name: Build zip
        run: bash bin/build-plugin-zip.sh -d

      - name: Deploy nightly build
        uses: WebFreak001/deploy-nightly@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 80943895 is the release ID of this nightly release https://github.com/woocommerce/woocommerce-blocks/releases/tag/nightly
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/80943895/assets{?name,label}
          release_id: 80943895
          asset_path: woocommerce-gutenberg-products-block.zip
          asset_name: woocommerce-blocks-${{ matrix.build }}-nightly.zip
          asset_content_type: application/zip
          max_releases: 1
  update:
    name: Update nightly tag commit ref
    runs-on: ubuntu-20.04
    steps:
      - name: Update nightly tag
        uses: richardsimko/github-tag-action@v1.0.5
        with:
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}