on:
    pull_request:
        types: [opened, synchronize, closed]
    push:
    issues:
        types: [edited]
name: Project management automations
permissions:
  pull-requests: write
  actions: write
jobs:
    project-management-automation:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: trunk
            - uses: woocommerce/automations@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  automations: todos
