name: Check Modified Assets

on:
    pull_request:

jobs:
    check-typescript-errors-with-trunk:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Cache node modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.OS }}-build-${{ secrets.CACHE_VERSION }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-build-${{ secrets.CACHE_VERSION }}-${{ env.cache-name }}-
                      ${{ runner.OS }}-build-${{ secrets.CACHE_VERSION }}-
            - name: Use Node.js 16.13.2
              uses: actions/setup-node@v1
              with:
                  node-version: 16.13.2
            - name: npm install
              run: |
                  npm ci
                  npm run ts:monitor
            - name: Download assets (trunk)
              uses: actions/checkout@v2
              with:
                  ref: trunk
                  path: trunk

            - name: Monitor TypeScript Errors
              uses: ./.github/monitor-typescript-errors
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  compare: checkstyle.xml
                  main_branch_folder: trunk
